# Generated by Django 4.1.3 on 2023-03-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalparty',
            name='state',
        ),
    ]
