# Generated by Django 4.1.3 on 2023-04-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0006_alter_voter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
