# Generated by Django 4.1.3 on 2023-04-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0008_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='cand_level_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('candidate_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.candidatelevel')),
            ],
        ),
    ]
