# Generated by Django 4.1.3 on 2023-04-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0009_cand_level_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='voters_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.voting')),
            ],
        ),
    ]
