# Generated by Django 4.1.3 on 2023-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0010_voters_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voted',
        ),
        migrations.AddField(
            model_name='voting',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='voters_vote',
        ),
    ]
