# Generated by Django 4.1.3 on 2023-04-19 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote_app', '0011_remove_voter_voted_voting_voted_delete_voters_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='cand_level_url',
        ),
    ]
