# Generated by Django 4.1.3 on 2023-04-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0012_voting_user_delete_cand_level_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='user',
        ),
    ]
