# Generated by Django 4.1.3 on 2023-04-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0013_remove_voting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='candidate_name',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
