# Generated by Django 4.1.3 on 2023-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0019_voting_v_lg_voting_v_state_voting_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='vote_hash',
            field=models.CharField(default=False, max_length=225),
        ),
    ]
