# Generated by Django 4.1.3 on 2023-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0020_voting_vote_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='previous_vote_hash',
            field=models.CharField(default=False, max_length=225),
        ),
    ]
